FROM golang:1.7-alpine

COPY . /go/src/github.com/itoryio/docme
WORKDIR /go/src/github.com/itoryio/docme

RUN set -ex \
    && apk add --no-cache --virtual .build-deps \
    gcc libc-dev git \
	&& go get github.com/Sirupsen/logrus \
	&& go get github.com/boltdb/bolt \
	&& go get github.com/spf13/cobra \
	&& go get github.com/docker/go-connections/sockets \
	&& cd /go/src/github.com/itoryio/docme/cmd/docme \
    && go install --ldflags '-extldflags "-static"' \
    && apk del .build-deps

CMD ["/go/bin/docme agent"]